services:
  ui-tests:
    image: ui-tests:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/usr/workspace/tests
      - ./allure-results:/usr/workspace/allure-results
    command: pdm run pytest -sv --alluredir=allure-results
    working_dir: /usr/workspace
    environment:
      - ENV=docker
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
    env_file:
      - .env

volumes:
  allure-results:
