name: UI Tests

on: [push]
#workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Checkout gh-pages repository to GitHub runner
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker-compose up --exit-code-from ui-tests || exit_code=$?
          echo "exit_code=${exit_code}" >> $GITHUB_ENV

      - name: Check container logs
        run: docker-compose logs

      - name: List Allure results
        run: ls -la allure-results

      - name: Copy history from gh-pages to allure-results
        run: |
          mkdir -p allure-results/history
          if [ -d ".github/gh-pages/history" ]; then
            cp -R ./.github/gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure report
        run: |
          echo "Generating Allure report..."
          docker-compose run ui-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          cp -R allure-report/history/* ./.github/gh-pages/history/ || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
