name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout gh-pages repository to GitHub runner
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker-compose up --exit-code-from regression || exit_code=$?
          echo "::set-output name=exit_code::$exit_code"

      - name: Copy history from gh-pages to allure-results
        run: |
          mkdir -p allure-results/history
          cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          echo "Generating Allure report..."
          docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
